Repository LeoMoriLima/ZabaFood, pull requests merged in 2024-04, with the labels that each got.

#87 feat: Added payment and pay confirmation pages related files
  public/assets/images/credit-card-icon.svg
  public/assets/images/payment-slip-icon.svg
  public/assets/images/pix-icon.svg
  public/components/CheckoutPage.js
  public/components/PaymentConfirmationPage.js
  public/components/PaymentPage.js
  public/js/routes.js
  public/pages/payconfirmation.js
  public/pages/payment.js
  public/style.css
Labels: feat, frontend

#92 feat: added a loading component to carousel.
  public/assets/images/zaba-leaves-loading.png
  public/components/Carousel.js
  public/components/LoadingComponent.js
  public/style.css
Labels: feat, backend

#93 feat: Added user setting pages and infos on left menu user page
  public/assets/images/menu-user-icon.svg
  public/assets/images/save-icon.svg
  public/components/userAccountPage.js
  public/components/userOrdersContent.js
  public/components/userSettingContent.js
  public/style.css
  src/controller/userController.js
  src/repository/userRepository.js
  src/services/userServices.js
Labels: feat, frontend

#94 feat: Added user balance on header
  public/components/NavMain.js
  public/style.css
Labels: feat, frontend

#95 fix and feat: fixed some bugs and included credit_balance fetch
  public/components/CartModal.js
  public/components/CheckoutPage.js
  public/components/DivRegister.js
  public/components/NavMain.js
  public/components/PaymentConfirmationPage.js
  public/components/PaymentPage.js
  public/style.css
  src/controller/userController.js
  src/repository/userRepository.js
  src/routes/userRoutes.js
  src/services/userServices.js
Labels: bug, frontend, backend, fix

#96 fix: Fixed CartModal to update when a product is added to cart
  public/components/CartModal.js
  public/style.css
Labels: frontend, fix

#97 fix: made home page and NavMain load faster
  public/components/Carousel.js
  public/components/CartModal.js
  public/components/CategoryModal.js
  public/components/NavMain.js
  public/components/ProductBanner.js
  public/style.css
Labels: frontend, fix

#98 fix and feat: fixed issue allowing adding to cart without being logged in and added loading indicator when adding products to cart
  public/assets/images/check-icon.svg
  public/assets/images/simple-loading.svg
  public/components/ProductCard.js
Labels: feat, frontend, fix

#99 fix and feat: Fixed some CSS issues and added a message component
  public/components/DivLogin.js
  public/components/DivRegister.js
  public/components/MainProductCard.js
  public/components/MessageComponent.js
  public/components/MessageContainer.js
  public/components/NavMain.js
  public/pages/about.js
  public/pages/cart.js
  public/pages/checkout.js
  public/pages/confirmation.js
  public/pages/contact.js
  public/pages/home.js
  public/pages/login.js
  public/pages/myaccount.js
  public/pages/notFound.js
  public/pages/payconfirmation.js
  public/pages/payment.js
  public/pages/policy.js
  public/pages/product.js
  public/pages/products.js
  public/pages/register.js
  public/pages/terms.js
  public/style.css
Labels: frontend

#100 feat: Added possibility to delete product from cart
  public/assets/images/delete-icon.svg
  public/components/CartPage.js
  public/style.css
  src/services/cartProductServices.js
Labels: feat, frontend, backend, change

#101 feat and fix: improved loading speed of product and products pages and added skeletons for product-related components
  public/components/MainProductSkeleton.js
  public/components/ProductCardRecommendedSkeleton.js
  public/components/ProductCardSkeleton.js
  public/components/ProductMain.js
  public/components/ProductsMain.js
  public/style.css
Labels: enhancement, feat, frontend, fix

#102 feat: changed deleteCartProduct to update total column from cart table
  src/repository/cartProductRepository.js
  src/services/cartProductServices.js
Labels: feat, backend

#103 Added validations, validations messages and performance improvements
  public/components/CartPage.js
  public/components/CheckoutPage.js
  public/components/PaymentPage.js
  public/pages/payment.js
  public/style.css
  src/controller/cartProductController.js
  src/controller/creditTransactionController.js
  src/services/cartProductServices.js
Labels: feat, frontend, backend, change

#104 feat and fix: added products-category-filter to products page and fixed some img src
  public/assets/images/category_template_filled.svg
  public/components/AboutPage.js
  public/components/AdminAccountPage.js
  public/components/AdminAddProductPage.js
  public/components/ArrowButton.js
  public/components/CartPage.js
  public/components/CategoryModal.js
  public/components/CheckoutPage.js
  public/components/ContactPage.js
  public/components/ImageLine.js
  public/components/LoadingComponent.js
  public/components/NavFooterMain.js
  public/components/NavLoginRegister.js
  public/components/NavMain.js
  public/components/PaymentPage.js
  public/components/PolicyPage.js
  public/components/ProductCard.js
  public/components/ProductsMain.js
  public/components/TermsPage.js
  public/components/TypeProductBanner.js
  public/components/inputEntry.js
  public/components/mainBanner.js
  public/components/userAccountPage.js
  public/components/userAddressContent.js
  public/components/userOrdersContent.js
  public/components/userSettingContent.js
  public/js/routes.js
  public/pages/products.js
  public/style.css
  src/controller/productController.js
  src/repository/productRepository.js
  src/services/cartProductServices.js
  src/services/productServices.js
Labels: feat, frontend, backend, fix

#105 feat: Added admin modify product page and product type control
  public/assets/images/product-type-icon.svg
  public/components/AdminAccountPage.js
  public/components/AdminAddProductPage.js
  public/components/AdminModifyProductPage.js
  public/components/AdminProductTypePage.js
  public/components/userSettingContent.js
  public/style.css
Labels: feat, frontend

#106 fix: Fixed a icon src in adminProductTypePage
  public/components/AdminProductTypePage.js
  public/style.css
  src/services/cartProductServices.js
Labels: frontend, fix

#107 feat: possibility of searching through the bar
  public/assets/images/not-found.svg
  public/components/CategoryModal.js
  public/components/NavMain.js
  public/components/NotFound.js
  public/components/ProductsMain.js
  public/style.css
  src/controller/productController.js
  src/repository/productRepository.js
  src/services/productServices.js
Labels: feat, frontend, backend

#108 fix: fixed the issue with deleting images in userAddressContent and made some CSS fixes
  public/components/userAddressContent.js
  public/style.css
Labels: frontend, fix

#109 fix: Fixed product filtering by type, corrected user address page issues, and made some CSS enhancements
  public/components/ProductsMain.js
  public/components/userAddressContent.js
  public/style.css
  src/controller/addressController.js
Labels: frontend, backend, fix

#110 fix: Fixed initial page style to better adapt to smaller pages
  public/assets/images/card-icon.svg
  public/assets/images/delivery-truck.svg
  public/assets/images/percentage-icon.svg
  public/assets/images/sign-icon.svg
  public/components/Carousel.js
  public/components/NavFooterMain.js
  public/components/mainBanner.js
  public/style.css
Labels: frontend, fix

#111 feat: added order management to admin account page
  public/assets/images/notes-icon.svg
  public/components/AdminAccountPage.js
  public/components/AdminOrderPage.js
  public/components/ButtonComponent.js
  public/style.css
  src/controller/cartController.js
  src/repository/cartRepository.js
  src/services/cartServices.js
Labels: feat, frontend, backend

#112 fix: Fixed buy product related pages style to better adapt to smaller pages
  public/style.css
Labels: frontend, fix

#113 feat: added delivered confirmation at user account page
  public/components/userOrdersContent.js
  public/style.css
  src/repository/cartRepository.js
Labels: feat, frontend, backend

#115 feat and fix: added a new route to product and fixed admin page style
  public/assets/images/product-type-icon.svg
  public/components/AdminAccountPage.js
  public/components/AdminAddProductPage.js
  public/components/AdminModifyProductPage.js
  public/components/AdminOrderPage.js
  public/components/ProductMain.js
  public/components/ProductsMain.js
  public/components/inputEntry.js
  public/style.css
  src/controller/productController.js
  src/repository/productRepository.js
  src/routes/productRoutes.js
  src/services/productServices.js
Labels: feat, frontend, backend, fix

#116 change: Changed product banner style
  public/components/ProductBanner.js
  public/style.css
Labels: frontend, change

#118 feat: Added links to products page on products cart modal
  public/components/CartModal.js
  public/style.css
Labels: feat, frontend

#120 fix and change : Adjusted performance and change style of /myaccount
  public/components/AdminModifyProductPage.js
  public/components/AdminProductTypePage.js
  public/components/userAccountPage.js
  public/components/userAddressContent.js
  public/components/userOrdersContent.js
  public/components/userSettingContent.js
  public/style.css
Labels: frontend, fix, change

#122 feat and fix: added stock reduction transaction and made some bug fixes
  public/components/CheckoutPage.js
  public/components/MainProductCard.js
  src/controller/cartProductController.js
  src/repository/cartProductRepository.js
  src/repository/cartRepository.js
  src/routes/cartProductRoutes.js
  src/services/cartProductServices.js
Labels: feat, backend, fix

#123 feat and fix: fixed skeleton div and added message component in user setting content
  public/components/AdminModifyProductPage.js
  public/components/CartPage.js
  public/components/NavMain.js
  public/components/ProductBanner.js
  public/components/userAccountPage.js
  public/components/userOrdersContent.js
  public/components/userSettingContent.js
  public/style.css
Labels: feat, frontend, fix

#124 fix: Fixed produc page style to better adapt to smaller pages
  public/components/MainProductCard.js
  public/components/ProductMain.js
  public/style.css
Labels: frontend, fix

#125 change: change style.css on payment page
  public/style.css
Labels: frontend, change

#126 fix: Fixed payment page style to better adapt to smaller pages
  public/components/PaymentConfirmationPage.js
  public/style.css
Labels: frontend, fix

#127 feat: Added route to add a icon image on product type
  public/components/AdminProductTypePage.js
  public/style.css
  src/controller/productTypeController.js
  src/repository/productTypeRepository.js
  src/services/productTypeService.js
Labels: feat, frontend, backend

#128 feat: added address selection at checkout page and added adress_id to approved carts
  public/components/CheckoutPage.js
  public/components/ProductsMain.js
  public/style.css
  src/controller/addressController.js
  src/controller/cartController.js
  src/repository/addressRepository.js
  src/repository/cartRepository.js
  src/services/addressService.js
  src/services/cartServices.js
Labels: enhancement, feat, frontend, backend

#129 feat: added image to product type related components
  public/components/AdminProductTypePage.js
  public/components/CategoryModal.js
  public/components/TypeProductBanner.js
  public/index.html
  src/controller/productTypeController.js
  src/repository/productTypeRepository.js
  src/routes/productTypeRoutes.js
  src/services/productTypeService.js
Labels: feat, frontend, backend, fix

#130 fix: fixed some issues at AdminProductTypePage and Carousel and made some refinement in general
  public/components/AdminOrderPage.js
  public/components/AdminProductTypePage.js
  public/components/Carousel.js
  public/components/CheckoutPage.js
  public/components/MainProductCard.js
  public/components/userOrdersContent.js
  src/repository/cartRepository.js
Labels: frontend, backend, fix

#131 Fixed styles to better adapt on smaller pages
  public/components/DivRegister.js
  public/components/userAccountPage.js
  public/style.css
Labels: frontend, fix

#132 fix: fixed product page and carousel style
  public/components/Carousel.js
  public/components/MainProductCard.js
  public/components/MainProductSkeleton.js
  public/style.css
Labels: frontend, fix

#134 feat and fix: started media query in home page and fixed some style in home page
  public/components/Carousel.js
  public/style.css
Labels: feat, frontend, fix

#135 fix: fixed AdminOrderPage scroll and products dropdown not working
  public/components/AdminOrderPage.js
  public/style.css
  src/controller/cartController.js
  src/repository/cartRepository.js
Labels: frontend, backend, fix

#136 fix: fixed some styles from header, Cart page, Checkout page, About page, Terms page, Policy page and Admin order page
  public/components/CartPage.js
  public/components/CheckoutPage.js
  public/style.css
Labels: feat, frontend, fix

#137 feat and fix: Fixed discount logic in cart_product route
  public/components/Carousel.js
  public/components/CartPage.js
  public/components/CheckoutPage.js
  public/components/NoCreditsModal.js
  public/components/QuantityInput.js
  public/pages/home.js
  src/repository/cartProductRepository.js
  src/services/cartProductServices.js
Labels: feat, frontend, backend, fix

#138 fixed: login and register page style
  public/style.css
Labels: frontend, fix

#139 Fix: Added query to user and admin page
  public/style.css
Labels: frontend, fix

#140 fix: fixed some cart page, checkout page and stock related bugs
  public/components/CartPage.js
  public/components/CheckoutPage.js
  public/components/MainProductCard.js
  public/components/ProductCard.js
  public/style.css
  src/controller/cartController.js
  src/repository/addressRepository.js
  src/repository/cartRepository.js
  src/services/cartProductServices.js
Labels: frontend, backend, fix

#141 fix: adjust style media query in admin and user page
  public/style.css
Labels: frontend, fix

#142 fix: Fixed some loadings and cart modal
  public/components/AboutPage.js
  public/components/AdminAccountPage.js
  public/components/AdminAddProductPage.js
  public/components/AdminModifyProductPage.js
  public/components/AdminOrderPage.js
  public/components/AdminProductTypePage.js
  public/components/Carousel.js
  public/components/CartModal.js
  public/components/CartPage.js
  public/components/CategoryModal.js
  public/components/CheckoutPage.js
  public/components/ConfirmationPage.js
  public/components/ContactPage.js
  public/components/DivLogin.js
  public/components/DivRegister.js
  public/components/FooterMain.js
  public/components/InputEntry.js
  public/components/LoadingComponent.js
  public/components/MainBanner.js
  public/components/MainProductCard.js
  public/components/MainProductSkeleton.js
  public/components/MessageContainer.js
  public/components/NavFooterMain.js
  public/components/NavLoginRegister.js
  public/components/NavMain.js
  public/components/PaymentPage.js
  public/components/PolicyPage.js
  public/components/ProductBanner.js
  public/components/ProductCard.js
  public/components/ProductCardRecommended.js
  public/components/ProductCardRecommendedSkeleton.js
  public/components/ProductCardSkeleton.js
  public/components/ProductMain.js
  public/components/ProductsMain.js
  public/components/QuantityInput.js
  public/components/TermsPage.js
  public/components/Text-a.js
  public/components/TypeProductBanner.js
  public/components/UserAccountPage.js
  public/components/UserAddressContent.js
  public/components/UserOrdersContent.js
  public/components/UserSettingContent.js
  public/js/routes.js
  public/pages/confirmation.js
  public/pages/contact.js
  public/pages/home.js
  public/pages/myaccount.js
  public/pages/payconfirmation.js
  public/pages/policy.js
  public/pages/product.js
  public/style.css
Labels: frontend, fix, change

#143 fix: fixed AdminProductTypeModal.js, push state on categoryModal, navMain, productsMain and decoded uri component on typeProductBanner.js
  public/components/AdminProductTypePage.js
  public/components/CategoryModal.js
  public/components/NavMain.js
  public/components/ProductsMain.js
  public/components/TypeProductBanner.js
  public/style.css
Labels: frontend, fix

#144 fix: Fixed advantages bar and delete account modal
  public/style.css
Labels: frontend, fix

#145 change: changed PG.Client to PG.Pool
  src/controller/creditTransactionController.js
  src/db/postgresql.js
  src/repository/addressRepository.js
  src/repository/cartProductRepository.js
  src/repository/cartRepository.js
  src/repository/creditTransactionRepository.js
  src/repository/loginRepository.js
  src/repository/productRepository.js
  src/repository/productTypeRepository.js
  src/repository/userRepository.js
  src/services/creditTransactionServices.js
Labels: backend, fix, change

#146 feat and fix: Added user deleted status and changed id req.user in updateUserCreditBalance.js
  public/components/PaymentPage.js
  public/components/UserSettingContent.js
  src/app.js
  src/controller/userController.js
  src/repository/userRepository.js
  src/routes/userRoutes.js
  src/services/loginServices.js
  src/services/userServices.js
Labels: feat, frontend, backend, fix

#147 fix: Fixed some api path, ProductsMain term bug and some style
  public/components/AdminAccountPage.js
  public/components/AdminAddProductPage.js
  public/components/AdminModifyProductPage.js
  public/components/AdminProductTypePage.js
  public/components/NavMain.js
  public/components/ProductsMain.js
  public/components/UserAccountPage.js
  public/components/UserSettingContent.js
  public/style.css
  src/app.js
Labels: frontend, backend, fix

#151 fix: Prevented purchasing an empty cart, made some adjusts and corrected all indentation
  public/components/AdminAccountPage.js
  public/components/AdminAddProductPage.js
  public/components/AdminModifyProductPage.js
  public/components/AdminProductTypePage.js
  public/components/ArrowButton.js
  public/components/CartPage.js
  public/components/CheckoutPage.js
  public/components/ContactPage.js
  public/components/DivLogin.js
  public/components/DivRegister.js
  public/components/ImageLine.js
  public/components/InputEntry.js
  public/components/LoadingComponent.js
  public/components/MainBanner.js
  public/components/MainProductCard.js
  public/components/MainProductSkeleton.js
  public/components/NavFooterMain.js
  public/components/NavLoginRegister.js
  public/components/NavMain.js
  public/components/NoCreditsModal.js
  public/components/NotFound.js
  public/components/PaymentConfirmationPage.js
  public/components/PaymentPage.js
  public/components/PolicyPage.js
  public/components/ProductBanner.js
  public/components/ProductsMain.js
  public/components/QuantityInput.js
  public/components/TermsPage.js
  public/components/UserAccountPage.js
  public/components/UserAddressContent.js
  public/components/UserOrdersContent.js
  public/components/UserSettingContent.js
  public/style.css
  src/app.js
  src/controller/cartProductController.js
  src/controller/creditTransactionController.js
  src/controller/loginController.js
  src/controller/productController.js
  src/controller/productTypeController.js
  src/controller/userController.js
  src/db/postgresql.js
  src/middleware/permissionVerify.js
  src/repository/cartProductRepository.js
  src/repository/productRepository.js
  src/repository/userRepository.js
  src/routes/loginRoutes.js
  src/routes/productRoutes.js
  src/routes/productTypeRoutes.js
  src/services/addressService.js
  src/services/creditTransactionServices.js
  src/services/loginServices.js
  src/services/productServices.js
  src/services/userServices.js
Labels: frontend, fix

#153 fix: fixed updated change address
  public/components/AdminAccountPage.js
  public/components/AdminModifyProductPage.js
  public/components/AdminOrderPage.js
  public/components/CheckoutPage.js
Labels: frontend, fix
